# Do not edit this file. It is automatically generated by 'build-configs'.

default:
  @just --list

composer *args:
  just _exec php composer {{ args }}




artisan *args:
  docker compose run \
    --entrypoint php \
    --rm \
    --tty \
    php artisan {{ args }}

_exec +args:
  docker compose exec {{ args }}
